In [1]:
import numpy as np

In [2]:
# create an array

arr = np.array([32,34,56,76,43])

In [3]:
arr

array([32, 34, 56, 76, 43])

In [4]:
print(arr)

[32 34 56 76 43]


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr1 = np.array([32,34,56,76,43, 10.11])

In [7]:
arr1

array([32.  , 34.  , 56.  , 76.  , 43.  , 10.11])

In [8]:
arr1.dtype

dtype('float64')

In [9]:
arr1 / 2

array([16.   , 17.   , 28.   , 38.   , 21.5  ,  5.055])

In [10]:
arr2 = np.array([32,34,56,76,43, 10.11, 'Aditya'])

In [11]:
arr2

array(['32', '34', '56', '76', '43', '10.11', 'Aditya'], dtype='<U32')

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [16]:
np.arange(12, 5, -1.5)

array([12. , 10.5,  9. ,  7.5,  6. ])

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [40]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
x.ndim

2

In [24]:
x.shape

(4, 3)

In [27]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
x.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
x.size

12

In [31]:
x.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [32]:
x.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [34]:
x.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [35]:
x.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [45]:
x.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [46]:
x.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

### accessing elements

In [47]:
arr

array([32, 34, 56, 76, 43])

In [48]:
arr[2]

56

In [49]:
arr[1:]

array([34, 56, 76, 43])

In [50]:
arr[:-1]

array([32, 34, 56, 76])

In [51]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
x[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [53]:
x[0:3,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [54]:
y = np.array([34,34,56,43,34])

In [55]:
np.unique(y)

array([34, 43, 56])

In [58]:
(34 + 34 + 56 + 43 + 34) / 5

40.2

In [56]:
np.mean(y)

40.2

In [57]:
np.max(y)

56

In [59]:
np.min(y)

34

In [60]:
np.absolute(-22)

22

In [61]:
np.abs(22)

22

In [62]:
np.abs(-33)

33