In [1]:
# data: Salary_Data.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Salary_Data.csv')

In [4]:
df.head()

,YearsExperience,Salary
0,1.1,39343.0
1,1.3,46205.0
2,1.5,37731.0
3,2.0,43525.0
4,2.2,39891.0


In [6]:
x = df['YearsExperience'].values
x = x.reshape(30,1)
y = df['Salary']

### holdout

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                   random_state=0,
                                                   test_size= 0.25)

### build linear reg model

In [8]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [9]:
print('training:', lr.score(x_train, y_train))
print('testing:', lr.score(x_test, y_test))

training: 0.9395413526983522
testing: 0.9779208335417602


### K fold Method

In [10]:
from sklearn.model_selection import KFold

In [13]:
x.shape

(30, 1)

In [11]:
kf = KFold(n_splits= 5, random_state= 0, shuffle= True)

In [12]:
for train, test in kf.split(x, y):
    print(train, '\n', test)

[ 0  1  3  4  5  6  7  8  9 11 12 14 15 16 17 18 19 20 21 22 23 25 27 29] 
 [ 2 10 13 24 26 28]
[ 0  1  2  3  4  6  7  8  9 10 12 13 14 15 18 19 20 21 23 24 25 26 28 29] 
 [ 5 11 16 17 22 27]
[ 0  2  3  4  5  6  7  9 10 11 12 13 15 16 17 18 19 21 22 24 25 26 27 28] 
 [ 1  8 14 20 23 29]
[ 0  1  2  3  5  8 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27 28 29] 
 [ 4  6  7  9 18 19]
[ 1  2  4  5  6  7  8  9 10 11 13 14 16 17 18 19 20 22 23 24 26 27 28 29] 
 [ 0  3 12 15 21 25]


### Extract the train and test data

In [14]:
for train, test in kf.split(x, y):
    print('Train:', x[train].flatten())
    print('Test:', x[test].flatten())

Train: [ 1.1  1.3  2.   2.2  2.9  3.   3.2  3.2  3.7  4.   4.   4.5  4.9  5.1
  5.3  5.9  6.   6.8  7.1  7.9  8.2  9.   9.6 10.5]
Test: [ 1.5  3.9  4.1  8.7  9.5 10.3]
Train: [ 1.1  1.3  1.5  2.   2.2  3.   3.2  3.2  3.7  3.9  4.   4.1  4.5  4.9
  5.9  6.   6.8  7.1  8.2  8.7  9.   9.5 10.3 10.5]
Test: [2.9 4.  5.1 5.3 7.9 9.6]
Train: [ 1.1  1.5  2.   2.2  2.9  3.   3.2  3.7  3.9  4.   4.   4.1  4.9  5.1
  5.3  5.9  6.   7.1  7.9  8.7  9.   9.5  9.6 10.3]
Test: [ 1.3  3.2  4.5  6.8  8.2 10.5]
Train: [ 1.1  1.3  1.5  2.   2.9  3.2  3.9  4.   4.   4.1  4.5  4.9  5.1  5.3
  6.8  7.1  7.9  8.2  8.7  9.   9.5  9.6 10.3 10.5]
Test: [2.2 3.  3.2 3.7 5.9 6. ]
Train: [ 1.3  1.5  2.2  2.9  3.   3.2  3.2  3.7  3.9  4.   4.1  4.5  5.1  5.3
  5.9  6.   6.8  7.9  8.2  8.7  9.5  9.6 10.3 10.5]
Test: [1.1 2.  4.  4.9 7.1 9. ]


### Apply Kfold

In [18]:
for train, test in kf.split(x,y):
    lr.fit(x[train], y[train])
    print('Traning accuracy:', lr.score(x[train], y[train]))
    print('testing accuracy:', lr.score(x[test], y[test]), '\n')

Traning accuracy: 0.9411949620562126
testing accuracy: 0.988169515729126 

Traning accuracy: 0.9612542631539638
testing accuracy: 0.9257917429817739 

Traning accuracy: 0.9635908373578711
testing accuracy: 0.9252385867407542 

Traning accuracy: 0.9625173469912476
testing accuracy: 0.8785189123539608 

Traning accuracy: 0.9540189535215173
testing accuracy: 0.9646120517676184 



### Apply kfold to Classification

In [19]:
# data: banknotes.csv

In [20]:
df = pd.read_csv('banknotes.csv')

In [21]:
df.head()

,Variance,Skewness,Curtosis,Entropy,Class
0,3.62160,8.6661,-2.8073,-0.44699,0
1,4.54590,8.1674,-2.4586,-1.46210,0
2,3.86600,-2.6383,1.9242,0.10645,0
3,3.45660,9.5228,-4.0112,-3.59440,0
4,0.32924,-4.4552,4.5718,-0.98880,0


In [22]:
df.shape

(1372, 5)

In [23]:
x = df.drop('Class', axis = 1)
y = df['Class']

In [24]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [25]:
dt = DecisionTreeClassifier(random_state=0)

In [27]:
for train, test in kf.split(x, y):
    dt.fit(x.iloc[train,:], y[train])
    y_pred = dt.predict(x.iloc[test,:])
    print('Accuracy:', accuracy_score(y[test], y_pred), '\n')

Accuracy: 0.9927272727272727 

Accuracy: 0.9854545454545455 

Accuracy: 0.9671532846715328 

Accuracy: 0.9963503649635036 

Accuracy: 0.9671532846715328 



In [30]:
y.value_counts()

Class
0    762
1    610
Name: count, dtype: int64

In [34]:
print('0:', round(y.value_counts()[0]/ len(y) * 100,2))
print('1:', round(y.value_counts()[1]/ len(y) * 100,2))

0: 55.54
1: 44.46


In [37]:
# stratify holdout

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                   random_state=0,
                                                   stratify= y)

In [40]:
# training balance
print('0:', round(y_train.value_counts()[0]/ len(y_train) * 100,2))
print('1:', round(y_train.value_counts()[1]/ len(y_train) * 100,2))

0: 55.49
1: 44.51


In [41]:
# testing balance

print('0:', round(y_test.value_counts()[0]/ len(y_test) * 100,2))
print('1:', round(y_test.value_counts()[1]/ len(y_test) * 100,2))

0: 55.69
1: 44.31


### Stratify Kfold

In [42]:
print('0:', round(y[train].value_counts()[0]/ len(y[train]) * 100,2))
print('1:', round(y[train].value_counts()[1]/ len(y[train]) * 100,2))

0: 56.19
1: 43.81


In [45]:
for train, test in kf.split(x, y):
    print('0:', round(y[train].value_counts()[0]/ len(y[train]) * 100,2))
    print('1:', round(y[train].value_counts()[1]/ len(y[train]) * 100,2), '\n')

0: 55.15
1: 44.85 

0: 55.79
1: 44.21 

0: 54.64
1: 45.36 

0: 55.92
1: 44.08 

0: 56.19
1: 43.81 



In [46]:
from sklearn.model_selection import StratifiedKFold

In [47]:
skf = StratifiedKFold(n_splits= 5, random_state= 0, shuffle= True)

In [48]:
for train, test in skf.split(x, y):
    print('0:', round(y[train].value_counts()[0]/ len(y[train]) * 100,2))
    print('1:', round(y[train].value_counts()[1]/ len(y[train]) * 100,2), '\n')

0: 55.52
1: 44.48 

0: 55.52
1: 44.48 

0: 55.56
1: 44.44 

0: 55.56
1: 44.44 

0: 55.56
1: 44.44 



In [49]:
for train, test in skf.split(x, y):
    dt.fit(x.iloc[train,:], y[train])
    y_pred = dt.predict(x.iloc[test,:])
    print('Accuracy:', accuracy_score(y[test], y_pred), '\n')

Accuracy: 0.9854545454545455 

Accuracy: 0.9927272727272727 

Accuracy: 0.9890510948905109 

Accuracy: 0.9854014598540146 

Accuracy: 0.9671532846715328 

